### ISSUE TITLE
allow to import/export delta chat backups

### ISSUE THREAD

**Issue by dotlambda** [adbenitez/deltachat-cursed#13]
The Delta Chat Android and iOS apps allow the creation of backups. It should be possible to import these.

**Comment by adbenitez** [comment]
yes that planned, in the meantime I guess you can just extract the `.tar` backup and place the content in `~/.curseddelta/account/` or use the `--db` command line argument

**Comment by LeMeteore** [comment]
If you already have a plan of how it should be done, I would like to help on you on this task.

**Comment by adbenitez** [comment]
@LeMeteore hi, sorry, missed your comment, importing is actually easy:

```
account.import_all(path_to_tar_backup)
```
then the data is imported in current db/account (the database provided with `--db` should NOT be configured to be able to import backup)
