### ISSUE TITLE
Use urwid-readline?

### ISSUE THREAD

**Issue by pabzm** [adbenitez/deltachat-cursed#6]
Would you consider using [urwid-readline](https://github.com/rr-/urwid_readline)? I'd love that!

**Comment by adbenitez** [comment]
I will check it when I get some time (have to port my bots to the new deltabot api) thanks for the link! and help is welcome! this currently has a poor use of dc events

**Comment by adbenitez** [comment]
closed via https://github.com/adbenitez/deltachat-cursed/commit/e8b7f52fbdf9394307b99d83791125b4d7f0917b

**Comment by adbenitez** [comment]
@pabzm thanks a lot for sharing info about urwid_readline that was just what I needed :+1: 
was quite easy to use, just had to change some shortcuts that where already in use, enjoy!
