### ISSUE TITLE
setup as a second device

### ISSUE THREAD

**Issue by magdesign** [adbenitez/deltachat-cursed#91]
thanks for this great tool!

i am trying to setup an account which is alteady linked to an android device.

so i copied private_key, public_key and the extraced backup.sqlite but this does not seem to work. sadly i can not setup using the official deltchat client since it dows not run on mobilelinux. is there any chance to manualy import the public and private keys ?

**Comment by adbenitez** [comment]
hello @magdesign thanks for trying out Cursed Delta, I just added an import sub-command for you to import account from backup file, update your Cursed Delta to the new version:

```
pip install -U deltachat-cursed 
```

then check that you have the new version:

```
$ delta -v
0.10.0
```

then go to your Delta Chat in your Android device, go to `Settings > Chats and Media` at the end there is an option to create a backup file, backup your account, this will generate a `.tar` file in the Downloads folder, copy the file to the device where you have Cursed Delta then import it using the new `import` sub-command:

```
delta import /path/to/backup.tar
```

then you can start using your account just running `delta` command, notice that if you import several accounts, there is no account selector at the moment and you will need to know the account addresses to pass it with `delta -a` to open the desired account

enjoy! :tada:

**Comment by magdesign** [comment]
🚀 wow, you are amazing 😍

updated, imported the backup, it works!
finally a working deltachat client on postmarketos mobilelinux.

thank you so much!

**Comment by adbenitez** [comment]
you are welcome! at the moment the app has basic features, but for IRC-like chatting is good :sweat_smile:
