### ISSUE TITLE
use another name than 'delta'

### ISSUE THREAD

**Issue by magdesign** [adbenitez/deltachat-cursed#94]
just figured out that after installing some diff and colordiff tools, deltachat-cursed gets overwritten with the 'delta' command.

it would be way better to name it 'deltachat' or even 'deltachat-cursed'

thank you.

**Comment by adbenitez** [comment]
hi @magdesign you can already use it with `curseddelta` command, `delta` is just an alternative shortcut

**Comment by adbenitez** [comment]
I updated the readme to mention `curseddelta` and say that `delta` is just an alias/shortuct, thanks a lot for the feedback @magdesign 
 
closed by e1b7911
